CREATE TABLE TicketDB(
	TicketCode VARCHAR(10) PRIMARY KEY NOT NULL,
	TicketName VARCHAR(64) NOT NULL,
	CategoryName VARCHAR(64) NOT NULL,
	Price INT NOT NULL,
	EventDate DATETIME NOT NULL,
	Quota INT NOT NULL,
)

CREATE TABLE BookedTicketDB(
	BookedTicketId NVARCHAR(50) NOT NULL,
	TicketCode VARCHAR(10) FOREIGN KEY REFERENCES TicketDB(TicketCode) NOT NULL,
	Quantity INT NOT NULL,
	BookedEventDate DATETIME NOT NULL,
)